# Generated by Django 5.1.2 on 2024-11-02 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_vat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='provider.provider')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('item_price_with_vat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vat', models.IntegerField(default=19)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoicing.invoice')),
            ],
        ),
    ]
