# Generated by Django 5.1.2 on 2024-11-02 16:15

from django.apps import apps as global_apps
from django.db import migrations
import os
import csv


def forward(apps, schema_editor):
    db_model = apps.get_model("invoicing", "City")
    db_model.objects.all().delete()
    csv_path =  os.path.join(os.path.dirname(__file__), "cities.csv")
    with open(csv_path, newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            db_model.objects.create(**row)


class Migration(migrations.Migration):
    """

    populating the table of City via csv

    """
    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop)
    ]
