# Generated by Django 5.1.2 on 2024-11-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_alter_invoice_total_amount_alter_invoice_total_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefragment',
            name='product_name',
            field=models.CharField(default='Generic Product', max_length=30),
        ),
    ]
