# Generated by Django 5.1.2 on 2024-11-02 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_auto_20241102_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('customer_type', models.CharField(choices=[('Individual', 'Individual'), ('Legal Entity', 'Legal Entity')], max_length=20)),
                ('ssn', models.CharField(blank=True, max_length=17, null=True)),
                ('cif', models.CharField(blank=True, max_length=17, null=True)),
                ('company_name', models.CharField(blank=True, max_length=17, null=True)),
                ('street_name', models.CharField(blank=True, max_length=17, null=True)),
                ('iban', models.CharField(blank=True, max_length=30, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=17, null=True)),
                ('is_paying_tva', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoicing.city')),
            ],
        ),
    ]
