version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn base.wsgi:application --bind 0.0.0.0:8000
    working_dir: /code/gimtpetinvoice
    tty: true
    stdin_open: true
    volumes:
      - static_volume:/code/gimtpetinvoice/staticfiles
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    environment:
      - POSTGRES_USER=invoiceadmin
      - POSTGRES_PASSWORD=invoicesafepass
      - POSTGRES_DB=invoicedb
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - 55432:5432
    tty: true
    stdin_open: true
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/gimtpetinvoice/staticfiles
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
