# Generated by Django 5.1.2 on 2024-11-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_provider_provider_pr_cif_ae767f_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='cif',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='reg_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
