# Generated by Django 5.1.2 on 2024-11-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_alter_provider_cif_alter_provider_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
